services:
    vote:
        container_name: vote
        networks:
            - backend
            - frontend
        ports:
            - 5001:80
        volumes:
            - vote:/app
        image: vote
    result:
        container_name: result
        networks:
            - backend
            - frontend
        ports:
            - 5000:80
        volumes:
            - result:/app
        image: result
    worker:
        container_name: worker
        networks:
            - backend
        image: worker
    redis:
        container_name: redis
        networks:
            - backend
        image: redis
    postgres:
        container_name: db
        networks:
            - backend
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgresdb:/var/lib/postgresql/data
        image: postgres
networks:
    backend:
    frontend:
volumes:
    vote:
        name: vote
    result:
        name: result
    postgresdb:
        name: postgresdb
    